# Generated by Django 2.2 on 2021-09-12 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default=' ', max_length=50)),
                ('model', models.CharField(default=' ', max_length=50)),
                ('vin_number', models.CharField(blank=True, default='', max_length=17, null=True)),
                ('date_purchased', models.DateTimeField(auto_now_add=True)),
                ('date_last_serviced', models.DateTimeField(auto_now_add=True)),
                ('service_received', models.CharField(max_length=300)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicles', to='clients.Client')),
                ('serviced_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
