# Generated by Django 2.2 on 2021-09-12 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_vehicleinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinformation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='date_last_serviced',
            field=models.CharField(blank=True, default='', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='date_purchased',
            field=models.CharField(blank=True, default='', max_length=17, null=True),
        ),
    ]
