# Generated by Django 2.2 on 2021-09-12 01:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20210911_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinformation',
            name='date_last_serviced',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 12, 1, 20, 1, 216000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='date_purchased',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 12, 1, 20, 12, 509807, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
