# Generated by Django 2.2.4 on 2021-09-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20210911_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleInformation',
        ),
    ]
