# Generated by Django 2.2 on 2021-09-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinformation',
            name='date_last_serviced',
            field=models.CharField(blank=True, default='', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='date_purchased',
            field=models.CharField(blank=True, default='', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='service_received',
            field=models.CharField(blank=True, default='', max_length=17, null=True),
        ),
    ]
