# Generated by Django 2.2 on 2021-09-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20210912_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinformation',
            name='service_received',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
