# Generated by Django 2.2 on 2021-09-12 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20210912_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinformation',
            name='service_received',
            field=models.TextField(default=datetime.datetime(2021, 9, 12, 19, 28, 18, 476280, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
