# Generated by Django 2.2 on 2021-09-12 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20210912_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinformation',
            name='make',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='model',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='service_received',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='serviced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
